{{- if and .Values.oidc.enabled (not .Values.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeadjust.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeadjust.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.oidc.clientSecret | quote }}
  sessionSecret: {{ .Values.oidc.sessionSecret | quote }}
{{- end }}
{{- if and .Values.oidc.enabled (not .Values.oidc.existingTokenSecret) }}
{{- if .Values.oidc.saTokens }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeadjust.fullname" . }}-oidc-tokens
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeadjust.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $token := .Values.oidc.saTokens }}
  {{ $name }}: {{ $token | quote }}
  {{- end }}
{{- end }}
{{- end }}
